---
title: "Graphs FAIR CARE Paper"
author:
  - name: Rainer M Krug
    id: rmk
    orcid: 0000-0002-7490-0066
    email: Rainer@krugs.de
    affiliation: 
      - name: University of Zürich
        city: Zürich
        url: www.uzh.ch
    roles: [author, editor]
format:
    html:
        toc: true
        toc-depth: 4
        toc_expand: true
        embed-resources: true
        code-fold: true
        code-summary: 'Show the code'

---

```{r}
#| label: setup

library(ggplot2)
library(treemapify)
```

```{r}
figure <- read.csv("input/decisions.csv") |>
  dplyr::select(
    Decision,
    Stage,
    Total
  ) |>
  dplyr::filter(
    Decision != "Total"
  ) |>
  dplyr::arrange(
    Decision, Stage
  ) |>
  dplyr::mutate(
    Stage = paste0(Stage, "\n(", Total, ")")
  ) |>
  ggplot(
    aes(
      area = Total,
      fill = Decision,
      label = Stage,
      subgroup = Decision
    )
  ) +
  geom_treemap(
    layout = "squarified",
    color = "black",
    size = 2,
    radius = grid::unit(10, "pt")
  ) +
  scale_fill_manual(
    values = c("green", "yellow", "red"),
    breaks = c("Synergy", "Independent", "Trade-off")
  ) +
  # geom_treemap_subgroup_border() +
  #   geom_treemap_subgroup_text(
  #     place = "centre",
  #     grow = T,
  #     alpha = 1,
  #     colour = "black",
  #     fontface = "italic",
  #     min.size = 0
  #   ) +
  geom_treemap_text(
    colour = "black",
    place = "centre",
    reflow = TRUE
  )

figure

ggplot2::ggsave("figures/FAIR-CARE-Plots.png", figure)
ggplot2::ggsave("figures/FAIR-CARE-Plots.svg", figure)
ggplot2::ggsave("figures/FAIR-CARE-Plots.pdf", figure)
```

Download
- [svg](figures/FAIR-CARE-Plots.svg)
- [pdf](figures/FAIR-CARE-Plots.pdf)
- [png](figures/FAIR-CARE-Plots.png)